return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "lua",
      "bash",
      "c",
      "cmake",
      "cpp",
      "comment",
      "css",
      "dockerfile",
      "fish",
      "gitignore",
      "go",
      "haskell",
      "html",
      "java",
      "javascript",
      "json",
      "latex",
      "make",
      "python",
      "rust",
      "sql",
      "typescript",
      "yaml",
    },
    highlight = {
      enable = true,
      disable = { "latex" },
    },

    auto_install = true,
  },
}
